name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download NLTK data
      run: |
        python -m nltk.downloader punkt
        python -m nltk.downloader wordnet
        python -m nltk.downloader punkt_tab

    - name: Run script
      run: python wordnetify.py --database tinystories.sqlite --progress --file tests/sample.txt
