name: Run Wordnetify

on:
  push:
    paths:
      - .github/workflows/run-wordnetify.yml
      - wordnetify.py
      - tests/sample.txt
  pull_request:
    paths:
      - .github/workflows/run-wordnetify.yml
      - wordnetify.py
      - tests/sample.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip      
        pip install -r requirements.txt

    - name: Download NLTK data
      run: |
        python -m nltk.downloader punkt
        python -m nltk.downloader wordnet

    - name: Run wordnetify
      run: |
        python wordnetify.py --database sample.sqlite --progress --file tests/sample.txt

    - name: Check for successful execution
      run: echo "Wordnetify script executed successfully"
    - name: Upload sample.sqlite as artifact
      uses: actions/upload-artifact@v3
      with:
        name: sample-database
        path: sample.sqlite
