name: Sense Resolution Workflow

on:
  push:
    paths:
      - .github/workflows/sense-resolution.py
      - tests/sample.sql
      - generate_multisynset_batch.py
      - batchcheck.py
      - batchfetch.py
  pull_request:
    paths:
      - .github/workflows/sense-resolution.py
      - tests/sample.sql
      - generate_multisynset_batch.py
      - batchcheck.py
      - batchfetch.py

jobs:
  resolve_synsets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
    - name: Install SQLite3
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create sample.sqlite database
      run: |
        sqlite3 sample.sqlite < tests/sample.sql
    - name: Run generate_multisynset_batch.py
      continue-on-error: true
      run: |
        python3 generate_multisynset_batch.py --database sample.sqlite --batch-id-save-file .batchid.txt

    - name: Run batchcheck.py
      continue-on-error: true
      run: |
        python3 batchcheck.py --database sample.sqlite  --only-batch $(< .batchid.txt) --monitor

    - name: Run batchfetch.py
      continue-on-error: true
      run: |
        python3 batchfetch.py --database sample.sqlite --report-costs

    - name: Upload modified sample.sqlite
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: sample.sqlite
        path: sample.sqlite
